### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by TheArushiSingh** [ALPHAVIO/WordNook#1042]
### Feature request-
Will add a toggle to switch between dark mode and light mode.

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is. 

### Describe how this feature will be useful to our readers.
User will be able to switch between dark mode and light mode according to his convenience. 

#### Are you contributing under any open-source program ?

LGM-SOC
<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* It is adviced to take up/ work on only 2 issues at the same time.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by theBeginner86** [comment]
@TheArushiSingh I appreciate your enthusiasm for contributions. But I would request you to clone the repo and run the project on your system first. 
Actually, we already have this feature for Dark Mode.🙂

But if you still have some better idea to improve it further then that would be great. Do let us know if you want to improve it? Otherwise, we might have to close this issue as the feature already exists.

**Comment by TheArushiSingh** [comment]
Oh,I guess I didn't notice that
That was the only thing I was suggesting.
I'm closing this issue.
