### ISSUE TITLE
Improve Contact-Us form UI

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/WordNook#980]
### Feature request-
Make the contact-us form look like the other forms on the website. (like the login and sign-up form)

![image](https://user-images.githubusercontent.com/54665036/120489930-a21a1200-c3d5-11eb-9465-948ffd7af6b3.png)

How it should be styled - 
![image](https://user-images.githubusercontent.com/54665036/120489734-7dbe3580-c3d5-11eb-84d8-5a1dd516a357.png)

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Ayush0730** [comment]
@Aiswarika Are you still working on this issue?

**Comment by Pranav016** [comment]
> Hey, is anyone working on this??

You can work on this after assigning it to yourself.

**Comment by Amrutha1101** [comment]
Is anybody working on this issue?

**Comment by Amishakumari544** [comment]
@Amrutha1101 i am really sorry, i just forget about this , if i will not completed this by today , you can work on this, really sorry for this.

**Comment by saloni-15** [comment]
@Pranav016 
I have one doubt,
I have just cloned this repository and wanted to work on this issue, but on my localhost, the login and signup pages look like this

![image](https://user-images.githubusercontent.com/75828760/126074908-7a59416a-cd26-4dcc-a27f-c6fbaecdc440.png)

Not like the one you have shared.

![image](https://user-images.githubusercontent.com/75828760/126075000-1f0006da-6f34-4dac-b933-50465562a57a.png)

Just wanted to know what can be the issue so that I can work further?
